
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IntegrationServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IntegrationServiceSoap {


    /**
     * ForeTees Interface
     * 
     * @param otherProduct1Qty
     * @param acct
     * @param otherProductCode1
     * @param caddieFeeCode
     * @param greenFeeCode
     * @param otherProduct2Qty
     * @param cartFeeCode
     * @param greenFeeQty
     * @param otherProduct2
     * @param cartFeeQty
     * @param caddieFeeQty
     * @return
     *     returns org.tempuri.OnlineSaleResult
     */
    @WebMethod(operationName = "AddSaleOnline", action = "http://tempuri.org/AddSaleOnline")
    @WebResult(name = "AddSaleOnlineResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddSaleOnline", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddSaleOnline")
    @ResponseWrapper(localName = "AddSaleOnlineResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddSaleOnlineResponse")
    public OnlineSaleResult addSaleOnline(
        @WebParam(name = "acct", targetNamespace = "http://tempuri.org/")
        String acct,
        @WebParam(name = "greenFeeCode", targetNamespace = "http://tempuri.org/")
        String greenFeeCode,
        @WebParam(name = "greenFeeQty", targetNamespace = "http://tempuri.org/")
        int greenFeeQty,
        @WebParam(name = "cartFeeCode", targetNamespace = "http://tempuri.org/")
        String cartFeeCode,
        @WebParam(name = "cartFeeQty", targetNamespace = "http://tempuri.org/")
        int cartFeeQty,
        @WebParam(name = "caddieFeeCode", targetNamespace = "http://tempuri.org/")
        String caddieFeeCode,
        @WebParam(name = "caddieFeeQty", targetNamespace = "http://tempuri.org/")
        int caddieFeeQty,
        @WebParam(name = "otherProductCode1", targetNamespace = "http://tempuri.org/")
        String otherProductCode1,
        @WebParam(name = "otherProduct1Qty", targetNamespace = "http://tempuri.org/")
        int otherProduct1Qty,
        @WebParam(name = "otherProduct2", targetNamespace = "http://tempuri.org/")
        String otherProduct2,
        @WebParam(name = "otherProduct2Qty", targetNamespace = "http://tempuri.org/")
        int otherProduct2Qty);

    /**
     * ForeTees Interface
     * 
     * @param acct
     * @param productFeeCodes
     * @param productQty
     * @return
     *     returns org.tempuri.OnlineSaleResult
     */
    @WebMethod(operationName = "AddSaleOnlineV2", action = "http://tempuri.org/AddSaleOnlineV2")
    @WebResult(name = "AddSaleOnlineV2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddSaleOnlineV2", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddSaleOnlineV2")
    @ResponseWrapper(localName = "AddSaleOnlineV2Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddSaleOnlineV2Response")
    public OnlineSaleResult addSaleOnlineV2(
        @WebParam(name = "acct", targetNamespace = "http://tempuri.org/")
        String acct,
        @WebParam(name = "productFeeCodes", targetNamespace = "http://tempuri.org/")
        ArrayOfString productFeeCodes,
        @WebParam(name = "productQty", targetNamespace = "http://tempuri.org/")
        ArrayOfInt productQty);

    /**
     * ForeTees Interface
     * 
     * @param acct
     * @param productFeeCodes
     * @param productQty
     * @param transactionNotes
     * @return
     *     returns org.tempuri.OnlineSaleResult
     */
    @WebMethod(operationName = "AddSaleOnlineV2WithNotes", action = "http://tempuri.org/AddSaleOnlineV2WithNotes")
    @WebResult(name = "AddSaleOnlineV2WithNotesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddSaleOnlineV2WithNotes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddSaleOnlineV2WithNotes")
    @ResponseWrapper(localName = "AddSaleOnlineV2WithNotesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddSaleOnlineV2WithNotesResponse")
    public OnlineSaleResult addSaleOnlineV2WithNotes(
        @WebParam(name = "acct", targetNamespace = "http://tempuri.org/")
        String acct,
        @WebParam(name = "productFeeCodes", targetNamespace = "http://tempuri.org/")
        ArrayOfString productFeeCodes,
        @WebParam(name = "productQty", targetNamespace = "http://tempuri.org/")
        ArrayOfInt productQty,
        @WebParam(name = "transactionNotes", targetNamespace = "http://tempuri.org/")
        String transactionNotes);

    /**
     * ForeTees Interface
     * 
     * @param pRequests
     * @return
     *     returns org.tempuri.ArrayOfOnlineSaleResult
     */
    @WebMethod(operationName = "AddSaleOnlineMultiple", action = "http://tempuri.org/AddSaleOnlineMultiple")
    @WebResult(name = "AddSaleOnlineMultipleResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddSaleOnlineMultiple", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddSaleOnlineMultiple")
    @ResponseWrapper(localName = "AddSaleOnlineMultipleResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddSaleOnlineMultipleResponse")
    public ArrayOfOnlineSaleResult addSaleOnlineMultiple(
        @WebParam(name = "pRequests", targetNamespace = "http://tempuri.org/")
        ArrayOfOnlineSaleRequest pRequests);

}
