
package com.ngn.services._2007._03._20.scoreservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ScoreService", targetNamespace = "http://services.ngn.com/2007/03/20/ScoreService", wsdlLocation = "http://services.uat.ngn.com/scoreservice.asmx?WSDL")
public class ScoreService_Service
    extends Service
{

    private final static URL SCORESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.ngn.services._2007._03._20.scoreservice.ScoreService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.ngn.services._2007._03._20.scoreservice.ScoreService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://services.uat.ngn.com/scoreservice.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://services.uat.ngn.com/scoreservice.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SCORESERVICE_WSDL_LOCATION = url;
    }

    public ScoreService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScoreService_Service() {
        super(SCORESERVICE_WSDL_LOCATION, new QName("http://services.ngn.com/2007/03/20/ScoreService", "ScoreService"));
    }

    /**
     * 
     * @return
     *     returns ScoreService
     */
    @WebEndpoint(name = "ScoreService")
    public ScoreService getScoreService() {
        return super.getPort(new QName("http://services.ngn.com/2007/03/20/ScoreService", "ScoreService"), ScoreService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScoreService
     */
    @WebEndpoint(name = "ScoreService")
    public ScoreService getScoreService(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.ngn.com/2007/03/20/ScoreService", "ScoreService"), ScoreService.class, features);
    }

}
