//----------DHTML Menu Created using AllWebMenus PRO ver 3.1-#532---------------
//C:\JAVA\Tomcat\webapps\v5\web utilities\proshop\ForeteesProshop.awm
var awmMenuName='foreteesProshop_sub';
var awmLibraryBuild=532;
var awmLibraryPath='/awmData-foreteesProshop';
var awmImagesPath='/awmData-foreteesProshop';
var awmSupported=(navigator.appName + navigator.appVersion.substring(0,1)=="Netscape5" || document.all || document.layers || navigator.userAgent.indexOf('Opera')>-1)?1:0;
if (awmAltUrl!='' && !awmSupported) window.location.replace(awmAltUrl);
if (awmSupported){
var awmMenuPath;
if (document.layers) mpi=((document.images['awmMenuPathImg-foreteesProshop_sub'])?document.images['awmMenuPathImg-foreteesProshop_sub'].src:document.layers['xawmMenuPathImg-foreteesProshop_sub'].document.images['awmMenuPathImg-foreteesProshop_sub'].src); else mpi=document.images['awmMenuPathImg-foreteesProshop_sub'].src;
awmMenuPath=mpi.substring(0,mpi.length-16);
while (awmMenuPath.search("'")>-1) {awmMenuPath=awmMenuPath.replace("'", "&#39;");}
var nua=navigator.userAgent,scriptNo=(nua.indexOf('Safari')>-1)?7:(nua.indexOf('Gecko')>-1)?2:((document.layers)?3:((nua.indexOf('Opera')>-1)?4:((nua.indexOf('Mac')>-1)?5:((nua.indexOf('Konqueror')>-1)?6:1))));
document.write("<SCRIPT SRC='"+awmMenuPath+awmLibraryPath+"/awmlib"+scriptNo+".js'><\/SCRIPT>");
var n=null;
awmzindex=100;
}

var awmSubmenusFrame='';
var awmSubmenusFrameOffset=0;
var awmOptimize=1;
var awmforeteesProshop_sub_1,awmforeteesProshop_sub_3,awmforeteesProshop_sub_4,awmforeteesProshop_sub_5,awmforeteesProshop_sub_6,awmforeteesProshop_sub_7;
function awmBuildMenu(){if(awmSupported){
awmMenuName='foreteesProshop_sub_1';
awmCreateCSS(0,1,0,n,'#CCCCAA',n,n,n,'solid',1,'#336633',0,0);
awmCreateCSS(1,2,0,'#336633','#CCCCAA',n,'bold 11px sans-serif',n,'solid',1,'#CCCCAA',0,1);
awmCreateCSS(0,2,0,'#000000','#F5F5DC',n,'bold 11px sans-serif',n,'solid',2,'#F5F5DC',0,1);
awmCreateCSS(0,2,0,'#800040','#F5F5DC',n,'bold 11px sans-serif',n,'solid',2,'#F5F5DC',0,1);
awmCreateCSS(1,2,0,'#336633','#CCCCAA',n,'bold 11px sans-serif',n,'none',1,'#CCCCAA',0,1);
var s0=awmCreateMenu(1,0,-1,0,0,0,0,1,0,0,0,0,0,0,n,n,"",n,1,0,1,0,"awmhidediv();","awmshowdiv();",100);
awmforeteesProshop_sub_1=s0;
it=s0.addItem(1,2,3,"&nbsp;&nbsp;Current Tee Sheets&nbsp;&nbsp;",n,n,"View the current tee sheets.","",n,n,"exeMenuAction('servlet/Proshop_select', 'get')",n,n);
it=s0.addItem(4,2,3,"&nbsp;&nbsp;Old Tee Sheets&nbsp;&nbsp;",n,n,"View or edit past tee sheets.","",n,n,"exeMenuAction('servlet/Proshop_oldsheets', 'get')",n,n);
it=s0.addItem(1,2,3,"&nbsp;&nbsp;Today's Tee Sheet&nbsp;&nbsp;",n,n,"View today&#39;s tee sheet.","",n,n,"exeMenuAction('servlet/Proshop_sheet?index=0', 'post')",n,n);
s0.pm.buildMenu();
awmMenuName='foreteesProshop_sub_3';
awmImagesColl=['green_haschild.gif',10,10];
awmCreateCSS(0,1,0,n,'#CCCCAA',n,n,n,'solid',1,'#336633',0,0);
awmCreateCSS(1,2,0,'#336633','#CCCCAA',n,'bold 11px sans-serif',n,'solid',1,'#CCCCAA',0,1);
awmCreateCSS(0,2,0,'#000000','#F5F5DC',n,'bold 11px sans-serif',n,'solid',2,'#F5F5DC',0,1);
awmCreateCSS(0,2,0,'#800040','#F5F5DC',n,'bold 11px sans-serif',n,'solid',2,'#F5F5DC',0,1);
var s0=awmCreateMenu(1,0,-1,0,0,0,0,1,0,0,0,0,0,0,n,n,"",n,1,0,1,0,"awmhidediv();","awmshowdiv();",100);
awmforeteesProshop_sub_3=s0;
it=s0.addItem(1,2,3,"&nbsp;&nbsp;View Lesson Book&nbsp;&nbsp;",n,n,"View the lesson book or schedule a lesson.","",n,n,"exeMenuAction('servlet/Proshop_lesson', 'post')",n,n);
it=s0.addItemWithImages(1,2,3,"&nbsp;&nbsp;Configure Lesson Book&nbsp;&nbsp;",n,n,"",n,n,n,0,0,0,0,0,0,"",n,n,n,n,n);
var s1=it.addSubmenu(0,0,-1,0,0,0,0,0,n,n,"",n,1,0,1,0,n,n,100);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Add Lesson Type&nbsp;&nbsp;",n,n,"Add a lesson type for a specified lesson pro","",n,n,"exeMenuAction('servlet/Proshop_lesson?addltype=yes', 'post')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Edit Lesson Type&nbsp;&nbsp;",n,n,"Change the definition of a lesson type for a specific lesson pro.","",n,n,"exeMenuAction('servlet/Proshop_lesson?editltype=yes', 'post')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Add Lesson Times&nbsp;&nbsp;",n,n,"Add a block of times to your lesson book.","",n,n,"exeMenuAction('servlet/Proshop_lesson?addltime=yes', 'post')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Edit Lesson Times&nbsp;&nbsp;",n,n,"Edit a block of times in your lesson book.","",n,n,"exeMenuAction('servlet/Proshop_lesson?editltime=yes', 'post')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Add Group Lesson&nbsp;&nbsp;",n,n,"","",n,n,"exeMenuAction('servlet/Proshop_lesson?addlgrp=yes', 'post')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Edit Group Lesson&nbsp;&nbsp;",n,n,"","",n,n,"exeMenuAction('servlet/Proshop_lesson?editlgrp=yes', 'post')",n,n);
it=s0.addItem(1,2,3,"&nbsp;&nbsp;View or Edit Bios&nbsp;&nbsp;",n,n,"Edit a Pro&#39;s Biography.","",n,n,"exeMenuAction('servlet/Proshop_lesson?bio=yes', 'post')",n,n);
it=s0.addItemWithImages(1,2,3,"&nbsp;&nbsp;Lesson Pros&nbsp;&nbsp;",n,n,"Lesson Pros",n,n,n,0,0,0,0,0,0,"",n,n,n,n,n);
var s1=it.addSubmenu(0,0,-1,0,0,0,0,0,n,n,"",n,1,0,1,0,n,n,100);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Add Pro&nbsp;&nbsp;",n,n,"Add a pro to the list of lesson pros.","",n,n,"exeMenuAction('servlet/Proshop_lesson?addPro=yes', 'post')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Edit Pro&nbsp;&nbsp;",n,n,"Edit a Lesson Pro&#39;s settings.","",n,n,"exeMenuAction('servlet/Proshop_lesson?editPro=yes', 'post')",n,n);
it=s0.addItem(1,2,3,"&nbsp;&nbsp;Help - How Does This Work?&nbsp;&nbsp;",n,n,"","",n,n,"exeMenuAction('servlet/Proshop_help_lessons', 'get')",n,n);
s0.pm.buildMenu();
awmMenuName='foreteesProshop_sub_4';
awmCreateCSS(0,1,0,n,'#CCCCAA',n,n,n,'solid',1,'#336633',0,0);
awmCreateCSS(1,2,0,'#336633','#CCCCAA',n,'bold 11px sans-serif',n,'solid',1,'#CCCCAA',0,1);
awmCreateCSS(0,2,0,'#000000','#F5F5DC',n,'bold 11px sans-serif',n,'solid',2,'#F5F5DC',0,1);
awmCreateCSS(0,2,0,'#800040','#F5F5DC',n,'bold 11px sans-serif',n,'solid',2,'#F5F5DC',0,1);
var s0=awmCreateMenu(1,0,-1,0,0,0,0,1,0,0,0,0,0,0,n,n,"",n,1,0,1,0,"awmhidediv();","awmshowdiv();",100);
awmforeteesProshop_sub_4=s0;
it=s0.addItem(1,2,3,"&nbsp;&nbsp;View or Edit Lottery Requests&nbsp;&nbsp;",n,n,"Access member lottery requests for a selected day.","",n,n,"exeMenuAsUrl('servlet/Proshop_mlottery?requests=yes')",n,n);
it=s0.addItem(1,2,3,"&nbsp;&nbsp;View or Approve Lottery Results&nbsp;&nbsp;",n,n,"Access or approve a lottery that has been processed.","",n,n,"exeMenuAsUrl('servlet/Proshop_mlottery?approve=yes')",n,n);
s0.pm.buildMenu();
awmMenuName='foreteesProshop_sub_5';
awmImagesColl=['green_haschild.gif',10,10];
awmCreateCSS(0,1,0,n,'#CCCCAA',n,n,n,'solid',1,'#336633',0,0);
awmCreateCSS(1,2,0,'#336633','#CCCCAA',n,'bold 11px sans-serif',n,'solid',1,'#CCCCAA',0,1);
awmCreateCSS(0,2,0,'#000000','#F5F5DC',n,'bold 11px sans-serif',n,'solid',2,'#F5F5DC',0,1);
awmCreateCSS(0,2,0,'#800040','#F5F5DC',n,'bold 11px sans-serif',n,'solid',2,'#F5F5DC',0,1);
var s0=awmCreateMenu(1,0,-1,0,0,0,0,1,0,0,0,0,0,0,n,n,"",n,1,0,1,0,"awmhidediv();","awmshowdiv();",100);
awmforeteesProshop_sub_5=s0;
it=s0.addItem(1,2,3,"&nbsp;&nbsp;Member Logins&nbsp;&nbsp;",n,n,"Determine the number of logins for a member or group of members.","",n,n,"exeMenuAsUrl('servlet/Proshop_usereport')",n,n);
it=s0.addItem(1,2,3,"&nbsp;&nbsp;Tee Time Counts&nbsp;&nbsp;",n,n,"View statistics pertaining to the number of tee times made.","",n,n,"exeMenuAction('servlet/Proshop_reports?teetimes=yes', 'post')",n,n);
it=s0.addItem(1,2,3,"&nbsp;&nbsp;No Shows&nbsp;&nbsp;",n,n,"Gather statistics on members that are no-shows.","",n,n,"exeMenuAction('servlet/Proshop_reports?noshow=yes', 'post')",n,n);
it=s0.addItemWithImages(1,2,3,"&nbsp;&nbsp;Number of Rounds Played&nbsp;&nbsp;",n,n,"",n,n,n,0,0,0,0,0,0,"",n,n,n,n,n);
var s1=it.addSubmenu(0,0,-1,0,0,0,0,0,n,n,"",n,1,0,1,0,n,n,100);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Last Month, MTD, YTD&nbsp;&nbsp;",n,n,"Gather recent &#39;rounds played&#39; statistics.","",n,n,"exeMenuAction('servlet/Proshop_reports?round=all', 'post')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Today&nbsp;&nbsp;",n,n,"Gather &#39;rounds played&#39; statistics for today.","",n,n,"exeMenuAction('servlet/Proshop_reports?today=yes', 'post')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Custom Date Range&nbsp;&nbsp;",n,n,"Gather &#39;rounds played&#39; statistics for a specified date range.","",n,n,"exeMenuAction('servlet/Proshop_reports?custom=yes', 'post')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;By Member This Month&nbsp;&nbsp;",n,n,"Display a list totaling all member rounds played this month.","",n,n,"exeMenuAction('servlet/Proshop_report_member_rounds?period=this', 'post')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;By Member Last Month&nbsp;&nbsp;",n,n,"Display a list totaling all member rounds played last month.","",n,n,"exeMenuAction('servlet/Proshop_report_member_rounds?period=last', 'post')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;By Member This Year&nbsp;&nbsp;",n,n,"Display a list totaling all member rounds played this year.","",n,n,"exeMenuAction('servlet/Proshop_report_member_rounds?period=year', 'post')",n,n);
it=s0.addItem(1,2,3,"&nbsp;&nbsp;Display Diary&nbsp;&nbsp;",n,n,"Display listing of diary entries for specific dates.","",n,n,"exeMenuAction('servlet/Proshop_diary_report', 'post')",n,n);
it=s0.addItem(1,2,3,"&nbsp;&nbsp;Rounds Reports - Trial&nbsp;&nbsp;",n,n,"","",n,n,"exeMenuAction('servlet/Proshop_report_menu', 'get')",n,n);
it=s0.addItem(1,2,3,"&nbsp;&nbsp;Pace of Play&nbsp;&nbsp;",n,n,"","",n,n,"exeMenuAction('servlet/Proshop_report_pace', 'get')",n,n);
s0.pm.buildMenu();
awmMenuName='foreteesProshop_sub_6';
awmImagesColl=['green_haschild.gif',10,10];
awmCreateCSS(0,1,0,n,'#CCCCAA',n,n,n,'solid',1,'#336633',0,0);
awmCreateCSS(1,2,0,'#336633','#CCCCAA',n,'bold 11px sans-serif',n,'solid',1,'#CCCCAA',0,1);
awmCreateCSS(0,2,0,'#000000','#F5F5DC',n,'bold 11px sans-serif',n,'solid',2,'#F5F5DC',0,1);
awmCreateCSS(0,2,0,'#800040','#F5F5DC',n,'bold 11px sans-serif',n,'solid',2,'#F5F5DC',0,1);
var s0=awmCreateMenu(1,0,-1,0,0,0,0,1,0,0,0,0,0,0,n,n,"",n,1,0,1,0,"awmhidediv();","awmshowdiv();",100);
awmforeteesProshop_sub_6=s0;
it=s0.addItem(1,2,3,"&nbsp;&nbsp;Announcements&nbsp;&nbsp;",n,n,"Manage your announcement page (create, edit or upload).","",n,n,"exeMenuAction('servlet/Proshop_announce?menu=yes', 'post')",n,n);
it=s0.addItem(1,2,3,"&nbsp;&nbsp;Build Tee Sheets&nbsp;&nbsp;",n,n,"Build the tee sheets (after initial setup only).","",n,n,"exeMenuAction('servlet/Proshop_buildTees', 'get')",n,n);
it=s0.addItemWithImages(1,2,3,"&nbsp;&nbsp;Email&nbsp;&nbsp;",n,n,"",n,n,n,0,0,0,0,0,0,"",n,n,"exeMenuAction('servlet/Send_email', 'get')",n,n);
var s1=it.addSubmenu(0,0,-1,0,0,0,0,0,n,n,"",n,1,0,1,0,n,n,100);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Send Email&nbsp;&nbsp;",n,n,"Send email messages to a member or group of members.","",n,n,"exeMenuAction('servlet/Send_email', 'get')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;View Distribution Lists&nbsp;&nbsp;",n,n,"View your current email distribution lists.","",n,n,"exeMenuAction('servlet/Communication', 'get')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Add Distribution List&nbsp;&nbsp;",n,n,"Add a group of members to a list for quicker selection when sending emails.","",n,n,"exeMenuAction('servlet/Add_distributionlist','get')",n,n);
it=s0.addItemWithImages(1,2,3,"&nbsp;&nbsp;Search&nbsp;&nbsp;",n,n,"",n,n,n,0,0,0,0,0,0,"",n,n,n,n,n);
var s1=it.addSubmenu(0,0,-1,0,0,0,0,0,n,n,"",n,1,0,1,0,n,n,100);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Player's Current Tee Times&nbsp;&nbsp;",n,n,"Search for an individual player&#39;s current tee times.","",n,n,"exeMenuAction('servlet/Proshop_searchmem', 'get')",n,n);
it=s1.addItemWithImages(1,2,3,"&nbsp;&nbsp;Player's Past Tee Times&nbsp;&nbsp;",n,n,"Search for an individual player&#39;s past tee times.",n,n,n,0,0,0,0,0,0,"",n,n,n,n,n);
var s2=it.addSubmenu(0,0,-1,0,0,0,0,0,n,n,"",n,1,0,1,0,n,n,100);
it=s2.addItem(1,2,3,"&nbsp;&nbsp;For This Calendar Year&nbsp;&nbsp;",n,n,"Search for a player&#39;s past tee times during this calendar year.","",n,n,"exeMenuAction('servlet/Proshop_reports?subtee=cal', 'post')",n,n);
it=s2.addItem(1,2,3,"&nbsp;&nbsp;For Past 12 Months&nbsp;&nbsp;",n,n,"Search for a player&#39;s past tee times during the past 12 months.","",n,n,"exeMenuAction('servlet/Proshop_reports?subtee=year', 'post')",n,n);
it=s2.addItem(1,2,3,"&nbsp;&nbsp;Since Inception&nbsp;&nbsp;",n,n,"Search for a player&#39;s past tee times since the inception of ForeTees.","",n,n,"exeMenuAction('servlet/Proshop_reports?subtee=forever', 'post')",n,n);
it=s0.addItem(1,2,3,"&nbsp;&nbsp;Settings&nbsp;&nbsp;",n,n,"Change your password.","",n,n,"exeMenuAction('servlet/Proshop_services', 'get')",n,n);
s0.pm.buildMenu();
awmMenuName='foreteesProshop_sub_7';
awmImagesColl=['green_haschild.gif',10,10];
awmCreateCSS(0,1,0,n,'#CCCCAA',n,n,n,'solid',1,'#336633',0,0);
awmCreateCSS(1,2,0,'#336633','#CCCCAA',n,'bold 11px sans-serif',n,'solid',1,'#CCCCAA',0,1);
awmCreateCSS(0,2,0,'#000000','#F5F5DC',n,'bold 11px sans-serif',n,'solid',2,'#F5F5DC',0,1);
awmCreateCSS(0,2,0,'#800040','#F5F5DC',n,'bold 11px sans-serif',n,'solid',2,'#F5F5DC',0,1);
var s0=awmCreateMenu(1,0,-1,0,0,0,0,1,0,0,0,0,0,0,n,n,"",n,1,0,1,0,"awmhidediv();","awmshowdiv();",100);
awmforeteesProshop_sub_7=s0;
it=s0.addItemWithImages(1,2,3,"&nbsp;&nbsp;Club Setup&nbsp;&nbsp;",n,n,"",n,n,n,0,0,0,0,0,0,"",n,n,n,n,n);
var s1=it.addSubmenu(0,0,-1,0,0,0,0,0,n,n,"",n,1,0,1,0,n,n,100);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Club Options&nbsp;&nbsp;",n,n,"Maintain the system settings for your club.","",n,n,"exeMenuAsUrl('servlet/Proshop_club')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Guest Types&nbsp;&nbsp;",n,n,"Maintain the types of guests allowed at your club.","",n,n,"exeMenuAsUrl('servlet/Proshop_club?step2=yes')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Member Types&nbsp;&nbsp;",n,n,"Maintian the types of members specified to access your course(s).","",n,n,"exeMenuAsUrl('servlet/Proshop_club?step3=yes')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Membership Types&nbsp;&nbsp;",n,n,"Maintain the membership types that access your course(s).","",n,n,"exeMenuAsUrl('servlet/Proshop_club?step4=yes')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Membership Options&nbsp;&nbsp;",n,n,"Maintain the course access parameters for each membership type.","",n,n,"exeMenuAsUrl('servlet/Proshop_club?step5=yes')",n,n);
it=s0.addItem(1,2,3,"&nbsp;&nbsp;Course Parameters&nbsp;&nbsp;",n,n,"Maintain the course parameters for each course at your club.","",n,n,"exeMenuAsUrl('servlet/Proshop_parms')",n,n);
it=s0.addItemWithImages(1,2,3,"&nbsp;&nbsp;Block Tee Times&nbsp;&nbsp;",n,n,"",n,n,n,0,0,0,0,0,0,"",n,n,n,n,n);
var s1=it.addSubmenu(0,0,-1,0,0,0,0,0,n,n,"",n,1,0,1,0,n,n,100);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Build New Blocker&nbsp;&nbsp;",n,n,"Create a new Tee Time Blocker from scratch.","",n,n,"exeMenuAction('servlet/Proshop_addblock', 'get')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Copy an Existing Blocker&nbsp;&nbsp;",n,n,"Create a new Tee Time Blocker by copying and editing an existing blocker.","",n,n,"exeMenuAction('servlet/Proshop_block?copy=yes', 'get')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Edit an Existing Blocker&nbsp;&nbsp;",n,n,"Change the parameters of an existing Tee Time Blocker.","",n,n,"exeMenuAction('servlet/Proshop_block', 'get')",n,n);
it=s0.addItemWithImages(1,2,3,"&nbsp;&nbsp;Double Tees&nbsp;&nbsp;",n,n,"",n,n,n,0,0,0,0,0,0,"",n,n,"exeMenuAction('servlet/proshop_services.htm')",n,n);
var s1=it.addSubmenu(0,0,-1,0,0,0,0,0,n,n,"",n,1,0,1,0,n,n,100);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Build New Double Tee&nbsp;&nbsp;",n,n,"Create a new double tee from scratch.","",n,n,"exeMenuAsUrl('servlet/Proshop_adddbltee')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Copy an Existing Double Tee&nbsp;&nbsp;",n,n,"Create a new double tee by copying and editiing an existing double tee.","",n,n,"exeMenuAsUrl('servlet/Proshop_dbltee?copy=yes')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Edit an Existing Double Tee&nbsp;&nbsp;",n,n,"Change the parameters of an existing double tee.","",n,n,"exeMenuAsUrl('servlet/Proshop_dbltee')",n,n);
it=s0.addItemWithImages(1,2,3,"&nbsp;&nbsp;Event Setup&nbsp;&nbsp;",n,n,"",n,n,n,0,0,0,0,0,0,"",n,n,n,n,n);
var s1=it.addSubmenu(0,0,-1,0,0,0,0,0,n,n,"",n,1,0,1,0,n,n,100);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Build New Event&nbsp;&nbsp;",n,n,"Build a new Event from scratch.","",n,n,"exeMenuAsUrl('servlet/Proshop_addevnt')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Copy an Existing Event&nbsp;&nbsp;",n,n,"Build a new Event by copying and editing an existing event.","",n,n,"exeMenuAsUrl('servlet/Proshop_events?copy=yes')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Edit an Existing Event&nbsp;&nbsp;",n,n,"Change the parameters of an existing Event.","",n,n,"exeMenuAsUrl('servlet/Proshop_events')",n,n);
it=s0.addItemWithImages(1,2,3,"&nbsp;&nbsp;Lottery Setup&nbsp;&nbsp;",n,n,"",n,n,n,0,0,0,0,0,0,"",n,n,n,n,n);
var s1=it.addSubmenu(0,0,-1,0,0,0,0,0,n,n,"",n,1,0,1,0,n,n,100);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Build New Lottery&nbsp;&nbsp;",n,n,"Create a new Lottery ffrom scratch.","",n,n,"exeMenuAsUrl('servlet/Proshop_addlottery')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Edit an Existing Lottery&nbsp;&nbsp;",n,n,"Change the parameters of an existing Lottery.","",n,n,"exeMenuAsUrl('servlet/Proshop_lottery')",n,n);
it=s0.addItemWithImages(1,2,3,"&nbsp;&nbsp;Guest Restrictions&nbsp;&nbsp;",n,n,"",n,n,n,0,0,0,0,0,0,"",n,n,n,n,n);
var s1=it.addSubmenu(0,0,-1,0,0,0,0,0,n,n,"",n,1,0,1,0,n,n,100);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Build New Restriction&nbsp;&nbsp;",n,n,"Create a new guest Restriction from scratch.","",n,n,"exeMenuAction('servlet/Proshop_addgrest', 'get')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Copy an Existing Restriction&nbsp;&nbsp;",n,n,"Create a new Guest Restriction by copying and editing an existing restriction.","",n,n,"exeMenuAction('servlet/Proshop_grest?copy=yes', 'get')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Edit an Existing Restriction&nbsp;&nbsp;",n,n,"Change the parameters of an existing Guest Restriction.","",n,n,"exeMenuAction('servlet/Proshop_grest', 'get')",n,n);
it=s0.addItemWithImages(1,2,3,"&nbsp;&nbsp;Guest Quota Restrictions&nbsp;&nbsp;",n,n,"",n,n,n,0,0,0,0,0,0,"",n,n,n,n,n);
var s1=it.addSubmenu(0,0,-1,0,0,0,0,0,n,n,"",n,1,0,1,0,n,n,100);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Build New Restriction&nbsp;&nbsp;",n,n,"Create a new Guest Quota Restriction from scratch.","",n,n,"exeMenuAction('servlet/Proshop_addgqta', 'get')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Copy an Existing Restriction&nbsp;&nbsp;",n,n,"Create a new Guest Quota Restriction by copying and editing an existing restriction.","",n,n,"exeMenuAction('servlet/Proshop_gqta?copy=yes', 'get')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Edit an Existing Restriction&nbsp;&nbsp;",n,n,"Change the parameters of an existing Guest Quota Restriction.","",n,n,"exeMenuAction('servlet/Proshop_gqta', 'get')",n,n);
it=s0.addItemWithImages(1,2,3,"&nbsp;&nbsp;Member Type Restrictions&nbsp;&nbsp;",n,n,"",n,n,n,0,0,0,0,0,0,"",n,n,n,n,n);
var s1=it.addSubmenu(0,0,-1,0,0,0,0,0,n,n,"",n,1,0,1,0,n,n,100);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Build New Restriction&nbsp;&nbsp;",n,n,"Create a new Member Restriction from scratch.","",n,n,"exeMenuAsUrl('servlet/Proshop_addmrest')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Copy an Existing Restriction&nbsp;&nbsp;",n,n,"Create a new Member Restriction by copying and editing an existing restriction.","",n,n,"exeMenuAsUrl('servlet/Proshop_mrest?copy=yes')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Edit an Existing Restriction&nbsp;&nbsp;",n,n,"Change the parameters of an existing Member Restriction.","",n,n,"exeMenuAction('servlet/Proshop_mrest', 'get')",n,n);
it=s0.addItemWithImages(1,2,3,"&nbsp;&nbsp;Member Number Restrictions&nbsp;&nbsp;",n,n,"",n,n,n,0,0,0,0,0,0,"",n,n,n,n,n);
var s1=it.addSubmenu(0,0,-1,0,0,0,0,0,n,n,"",n,1,0,1,0,n,n,100);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Build New Restriction&nbsp;&nbsp;",n,n,"Create a new Member Number Restriction from scratch.","",n,n,"exeMenuAction('servlet/Proshop_addmNumrest', 'get')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Copy an Existing Restriction&nbsp;&nbsp;",n,n,"Create a new Member Number Restriction by copying and editing an existing restriction.","",n,n,"exeMenuAction('servlet/Proshop_mNumrest?copy=yes', 'get')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Edit an Existing Restriction&nbsp;&nbsp;",n,n,"Change the parameters of an existing Member Number Restriction.","",n,n,"exeMenuAction('servlet/Proshop_mNumrest', 'get')",n,n);
it=s0.addItemWithImages(1,2,3,"&nbsp;&nbsp;5-Some Restrictions&nbsp;&nbsp;",n,n,"",n,n,n,0,0,0,0,0,0,"",n,n,n,n,n);
var s1=it.addSubmenu(0,0,-1,0,0,0,0,0,n,n,"",n,1,0,1,0,n,n,100);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Build New Restriction&nbsp;&nbsp;",n,n,"Create a new 5-some Restriction from scratch.","",n,n,"exeMenuAction('servlet/Proshop_addfives', 'get')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Copy an Existing Restriction&nbsp;&nbsp;",n,n,"Create a new 5-some Restriction by copying and editing an existing restriction.","",n,n,"exeMenuAction('servlet/Proshop_fives?copy=yes', 'get')",n,n);
it=s1.addItem(1,2,3,"&nbsp;&nbsp;Edit an Existing Restriction&nbsp;&nbsp;",n,n,"Change the parameters of an existing 5-some Restriction.","",n,n,"exeMenuAction('servlet/Proshop_fives', 'get')",n,n);
s0.pm.buildMenu();}}
