
package com.ngn.services._2007._03._20.handicapservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HandicapService", targetNamespace = "http://services.ngn.com/2007/03/20/HandicapService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.ngn.services._2007._03._20.commondata.ObjectFactory.class,
    com.ngn.services._2007._03._20.headerdata.ObjectFactory.class,
    com.ngn.services._2007._03._20.handicapservice.ObjectFactory.class,
    com.ngn.services._2007._03._20.handicapdata.ObjectFactory.class
})
public interface HandicapService {


    /**
     * 
     * @param updateHandicapsRequest
     * @return
     *     returns com.ngn.services._2007._03._20.handicapservice.UpdateHandicapsResponse
     */
    @WebMethod(operationName = "UpdateHandicaps", action = "http://services.ngn.com/2007/03/20/HandicapService/UpdateHandicaps")
    @WebResult(name = "UpdateHandicapsResponse", targetNamespace = "http://services.ngn.com/2007/03/20/HandicapService", partName = "UpdateHandicapsResult")
    public UpdateHandicapsResponse updateHandicaps(
        @WebParam(name = "UpdateHandicapsRequest", targetNamespace = "http://services.ngn.com/2007/03/20/HandicapService", partName = "UpdateHandicapsRequest")
        UpdateHandicapsRequest updateHandicapsRequest);

    /**
     * 
     * @param fetchHandicapsByUserRequest
     * @return
     *     returns com.ngn.services._2007._03._20.handicapservice.FetchHandicapsResponse
     */
    @WebMethod(operationName = "FetchHandicapByUser", action = "http://services.ngn.com/2007/03/20/HandicapService/FetchHandicapByUser")
    @WebResult(name = "FetchHandicapsResponse", targetNamespace = "http://services.ngn.com/2007/03/20/HandicapService", partName = "FetchHandicapByUserResult")
    public FetchHandicapsResponse fetchHandicapByUser(
        @WebParam(name = "FetchHandicapByUserRequest", targetNamespace = "http://services.ngn.com/2007/03/20/HandicapService", partName = "FetchHandicapsByUserRequest")
        FetchHandicapByUserRequest fetchHandicapsByUserRequest);

    /**
     * 
     * @param fetchHandicapListByUserRequest
     * @return
     *     returns com.ngn.services._2007._03._20.handicapservice.FetchHandicapsResponse
     */
    @WebMethod(operationName = "FetchHandicapListByUser", action = "http://services.ngn.com/2007/03/20/HandicapService/FetchHandicapListByUser")
    @WebResult(name = "FetchHandicapsResponse", targetNamespace = "http://services.ngn.com/2007/03/20/HandicapService", partName = "FetchHandicapListByUserResult")
    public FetchHandicapsResponse fetchHandicapListByUser(
        @WebParam(name = "FetchHandicapListByUserRequest", targetNamespace = "http://services.ngn.com/2007/03/20/HandicapService", partName = "FetchHandicapListByUserRequest")
        FetchHandicapListByUserRequest fetchHandicapListByUserRequest);

    /**
     * 
     * @param fetchHandicapListByNetworkIdRequest
     * @return
     *     returns com.ngn.services._2007._03._20.handicapservice.FetchHandicapsResponse
     */
    @WebMethod(operationName = "FetchHandicapListByNetworkId", action = "http://services.ngn.com/2007/03/20/HandicapService/FetchHandicapListByNetworkId")
    @WebResult(name = "FetchHandicapsResponse", targetNamespace = "http://services.ngn.com/2007/03/20/HandicapService", partName = "FetchHandicapListByNetworkIdResult")
    public FetchHandicapsResponse fetchHandicapListByNetworkId(
        @WebParam(name = "FetchHandicapListByNetworkIdRequest", targetNamespace = "http://services.ngn.com/2007/03/20/HandicapService", partName = "FetchHandicapListByNetworkIdRequest")
        FetchHandicapListByNetworkIdRequest fetchHandicapListByNetworkIdRequest);

}
