
package com.ngn.services._2007._03._20.courseservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CourseService", targetNamespace = "http://services.ngn.com/2007/03/20/CourseService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.ngn.services._2007._03._20.headerdata.ObjectFactory.class,
    com.ngn.services._2007._03._20.coursedata.ObjectFactory.class,
    com.ngn.services._2007._03._20.courseservice.ObjectFactory.class
})
public interface CourseService {


    /**
     * 
     * @param fetchCoursesBySearchRequest
     * @return
     *     returns com.ngn.services._2007._03._20.courseservice.FetchCoursesResponse
     */
    @WebMethod(operationName = "FetchCoursesBySearch", action = "http://services.ngn.com/2007/03/20/CourseService/FetchCoursesBySearch")
    @WebResult(name = "FetchCoursesResponse", targetNamespace = "http://services.ngn.com/2007/03/20/CourseService", partName = "FetchCoursesBySearchResult")
    public FetchCoursesResponse fetchCoursesBySearch(
        @WebParam(name = "FetchCoursesBySearchRequest", targetNamespace = "http://services.ngn.com/2007/03/20/CourseService", partName = "FetchCoursesBySearchRequest")
        FetchCoursesBySearchRequest fetchCoursesBySearchRequest);

    /**
     * 
     * @param fetchClubsBySearchRequest
     * @return
     *     returns com.ngn.services._2007._03._20.courseservice.FetchClubsResponse
     */
    @WebMethod(operationName = "FetchClubsBySearch", action = "http://services.ngn.com/2007/03/20/CourseService/FetchClubsBySearch")
    @WebResult(name = "FetchClubsResponse", targetNamespace = "http://services.ngn.com/2007/03/20/CourseService", partName = "FetchClubsBySearchResult")
    public FetchClubsResponse fetchClubsBySearch(
        @WebParam(name = "FetchClubsBySearchRequest", targetNamespace = "http://services.ngn.com/2007/03/20/CourseService", partName = "FetchClubsBySearchRequest")
        FetchClubsBySearchRequest fetchClubsBySearchRequest);

    /**
     * 
     * @param fetchClubsBySourceRequest
     * @return
     *     returns com.ngn.services._2007._03._20.courseservice.FetchClubsResponse
     */
    @WebMethod(operationName = "FetchClubsBySource", action = "http://services.ngn.com/2007/03/20/CourseService/FetchClubsBySource")
    @WebResult(name = "FetchClubsResponse", targetNamespace = "http://services.ngn.com/2007/03/20/CourseService", partName = "FetchClubsBySourceResult")
    public FetchClubsResponse fetchClubsBySource(
        @WebParam(name = "FetchClubsBySourceRequest", targetNamespace = "http://services.ngn.com/2007/03/20/CourseService", partName = "FetchClubsBySourceRequest")
        FetchClubsBySourceRequest fetchClubsBySourceRequest);

    /**
     * 
     * @param fetchCourseByIdRequest
     * @return
     *     returns com.ngn.services._2007._03._20.courseservice.FetchCoursesResponse
     */
    @WebMethod(operationName = "FetchCourseById", action = "http://services.ngn.com/2007/03/20/CourseService/FetchCourseById")
    @WebResult(name = "FetchCoursesResponse", targetNamespace = "http://services.ngn.com/2007/03/20/CourseService", partName = "FetchCourseByIdResult")
    public FetchCoursesResponse fetchCourseById(
        @WebParam(name = "FetchCourseByIdRequest", targetNamespace = "http://services.ngn.com/2007/03/20/CourseService", partName = "FetchCourseByIdRequest")
        FetchCourseByIdRequest fetchCourseByIdRequest);

}
