
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IntegrationService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://70.89.104.149/CPSTestService/IntegrationService.asmx?WSDL")
public class IntegrationService
    extends Service
{

    private final static URL INTEGRATIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.tempuri.IntegrationService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.tempuri.IntegrationService.class.getResource(".");
            url = new URL(baseUrl, "http://70.89.104.149/PosExpressWS3/IntegrationService.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://70.89.104.149/CPSTestService/IntegrationService.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        INTEGRATIONSERVICE_WSDL_LOCATION = url;
    }

    public IntegrationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntegrationService() {
        super(INTEGRATIONSERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "IntegrationService"));
    }

    /**
     * 
     * @return
     *     returns IntegrationServiceSoap
     */
    @WebEndpoint(name = "IntegrationServiceSoap")
    public IntegrationServiceSoap getIntegrationServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "IntegrationServiceSoap"), IntegrationServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IntegrationServiceSoap
     */
    @WebEndpoint(name = "IntegrationServiceSoap")
    public IntegrationServiceSoap getIntegrationServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "IntegrationServiceSoap"), IntegrationServiceSoap.class, features);
    }

}
