
package org.ibsservices;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IBSWebMemberAPI", targetNamespace = "http://ibsservices.org/", wsdlLocation = "file:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/IBSWebMemberAPI.WSDL")
public class IBSWebMemberAPI
    extends Service
{

    private final static URL IBSWEBMEMBERAPI_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.ibsservices.IBSWebMemberAPI.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.ibsservices.IBSWebMemberAPI.class.getResource(".");
            url = new URL(baseUrl, "file:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/IBSWebMemberAPI.WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/IBSWebMemberAPI.WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IBSWEBMEMBERAPI_WSDL_LOCATION = url;
    }

    public IBSWebMemberAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IBSWebMemberAPI() {
        super(IBSWEBMEMBERAPI_WSDL_LOCATION, new QName("http://ibsservices.org/", "IBSWebMemberAPI"));
    }

    /**
     * 
     * @return
     *     returns IBSWebMemberAPISoap
     */
    @WebEndpoint(name = "IBSWebMemberAPISoap")
    public IBSWebMemberAPISoap getIBSWebMemberAPISoap() {
        return super.getPort(new QName("http://ibsservices.org/", "IBSWebMemberAPISoap"), IBSWebMemberAPISoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBSWebMemberAPISoap
     */
    @WebEndpoint(name = "IBSWebMemberAPISoap")
    public IBSWebMemberAPISoap getIBSWebMemberAPISoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://ibsservices.org/", "IBSWebMemberAPISoap"), IBSWebMemberAPISoap.class, features);
    }

    /**
     * 
     * @return
     *     returns IBSWebMemberAPISoap
     */
    @WebEndpoint(name = "IBSWebMemberAPISoap12")
    public IBSWebMemberAPISoap getIBSWebMemberAPISoap12() {
        return super.getPort(new QName("http://ibsservices.org/", "IBSWebMemberAPISoap12"), IBSWebMemberAPISoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBSWebMemberAPISoap
     */
    @WebEndpoint(name = "IBSWebMemberAPISoap12")
    public IBSWebMemberAPISoap getIBSWebMemberAPISoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://ibsservices.org/", "IBSWebMemberAPISoap12"), IBSWebMemberAPISoap.class, features);
    }

}
